[package]
name = "quartz_nbt"
version = "0.1.2"
authors = ["Cassy343", "maddymakesgames"]
edition = "2018"

description = "Provides support for serializing and deserializing Minecraft NBT data in binary and string form."
repository = "https://github.com/Rusty-Quartz/quartz_nbt"
license = "MIT"
readme = "README.md"

keywords = ["nbt", "minecraft", "data", "encode"]
categories = ["encoding", "parser-implementations"]

[dependencies]
byteorder = "1.4.3"
cesu8 = "1.1.0"
flate2 = "1.0.20"